version: '3.8'

services:
  nginx:
    image: nginx:alpine-slim
    environment:
      - VIRTUAL_HOST=demo.dev.local
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    networks:
      - default
      - web
  php:
    image: naild/phpdev:latest
    volumes:
      - .:/app
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  web:
    external: true